# syntax=docker/dockerfile:1

FROM golang:1.23-alpine AS build
RUN apk add --no-cache ca-certificates git
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.24.1

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /go/bin/goose /usr/local/bin/goose
COPY migrations ./migrations
ENTRYPOINT ["goose", "-dir", "/app/migrations"]
